# Generated by Django 3.0.5 on 2020-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='folder_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
