# Generated by Django 3.0.5 on 2020-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200423_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='number_of_chapters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
