# Generated by Django 3.0.5 on 2020-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_books_number_of_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapters',
            name='chapter_id',
            field=models.IntegerField(),
        ),
    ]
