# Generated by Django 3.0.5 on 2020-04-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200425_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapters',
            name='chapter_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
