# Generated by Django 3.0.5 on 2020-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20200425_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='chapter_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
