# Generated by Django 3.0.5 on 2020-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_chapters_chapter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='thumbnail_url',
            field=models.CharField(default='thumbnails/', max_length=100),
            preserve_default=False,
        ),
    ]
