# Generated by Django 3.0.5 on 2020-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_books_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='chapter_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
