# Generated by Django 3.0.5 on 2020-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_chapters_chapter_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='chapter_title',
            new_name='chapter_title_english',
        ),
        migrations.AddField(
            model_name='chapters',
            name='chapter_title_vernacular',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
